# docker-compose.yml
services:
  postgres_db:
    image: postgres:15
    container_name: users-api
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-martin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-users_api_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-users_api_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: